# Generated by Django 3.2.16 on 2023-09-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
