# Generated by Django 3.2.16 on 2023-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usersonline_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersonline',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
