# Generated by Django 3.2.16 on 2023-09-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usersonline_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersonline',
            old_name='online',
            new_name='status',
        ),
    ]
