# Generated by Django 3.2.16 on 2023-09-07 15:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_rename_online_usersonline_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersOnline',
            new_name='DisponivelPartida',
        ),
    ]
