# Generated by Django 3.2.16 on 2023-09-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_usersonline_disponivelpartida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisponivelPartida',
        ),
    ]
